:doctype: book
:icons: font
:hide-uri-scheme:

= Red Hat Integration - Camel K

== Camel K Capabilities

Red Hat Integration's Camel K is a light weight integration framework, built from the upstream Apache Camel K runtime.

Camel K runs natively on top of OpenShift and takes advantage of Quarkus, as a runtime, and can be used in conjunction with Serverless to allow for autoscaling of deployments.

Camel K gives developers the following advantages:

- Predefined integration templates, called *Kamelets*, which allows for quick configuration of integrations. Kamelets are pure Camel DSL and can embody all the logic that allows to consume or produce data from public SaaS or enterprise systems and only expose to the final users a clean interface that describes the expected parameters, input and output.

- Code in the form of Java, Groovy, Kotlin, JavaScript and XML or Yaml DSL deployment for quick deployment. 

- Container creation is automated by a code compilation optimized subsystem, called the integration platform.

- Multiple development tool support, for example Karavan a plugin for Visual Studio Code, and also a full CLI implementation 

Supports multiple traits, which can be enabled globally on integration platform level, or per deployment. Traits are automated and usually only requires a couple configuration parameters to be enabled. An example of a trait is tracing, 

Traits includes technologies like:

- 3scale (API Management), Swagger, OpenAPI
- Ingress Control
- Service Mesh, Serverless
- Jolokia, JVM 
- Health endpoints, Logging, tracing, Prometheus
- Deployment configuration, mounts, pull secrets, route, tolerations, resources

== Kamelets

Preconfigured Kamelets are shipped with Camel K, which includes a wide range of technologies.

****
[TIP]
.Kamelet Catalog
To see the current list of available Kamelets, see the Apache Camel Kamelets catalog:
    https://camel.apache.org/camel-kamelets/
****

On top of all the features like Kamelets and traits, Camel K also support standard Camel Components.

****
[TIP]
.Camel Components
To see the current list of available components, see the Apache Camel Component Documentation:
    https://camel.apache.org/components/
****


 