= Establishing an EDA Platform on OpenShift
Pieter Malan
:doctype: book
:icons: font
:hide-uri-scheme:

:appendix-caption: Exhibit
:sectnums:
:toc: macro


:toclevels: 2
:icons: font

:relfileprefix: ../
:outfilesuffix:
:sectnums:
:sectnumlevels: 6
:partnums:
:chapter-signifier: Chapter
:part-signifier: Part
:book: true
:pdf: true

:chapters-path: chapters/
:imagesdir: images/

toc::[]


[preface]
== What is Event-Driven Architecture ?

To understand what is the meaning of Event Driven Architecture, let see what the industry describe it as, by looking at different definitions given by vendors and analysts:


[quote, Google, https://www.gartner.com/en/information-technology/glossary/eda-event-driven-architecture#:~:text=Event%2Ddriven%20architecture%20(EDA)%20is%20a%20design%20paradigm%20in,one%20or%20more%20event%20notifications.]
An event-driven architecture is a software design pattern in which microservices react to changes in state, called events. Events can either carry a state (such as the price of an item or a delivery address) or events can be identifiers (a notification that an order was received or shipped, for example).


[quote, Gartner,https://www.gartner.com/en/information-technology/glossary/eda-event-driven-architecture#:~:text=Event%2Ddriven%20architecture%20(EDA)%20is%20a%20design%20paradigm%20in,one%20or%20more%20event%20notifications]
____
Event-driven architecture (EDA) is a design paradigm in which a software component executes in response to receiving one or more event notifications. EDA is more loosely coupled than the client/server paradigm because the component that sends the notification doesn’t know the identity of the receiving components at the time of compiling.
____

[quote, AWS, https://aws.amazon.com/event-driven-architecture/]
____
An event-driven architecture uses events to trigger and communicate between decoupled services and is common in modern applications built with microservices. An event is a change in state, or an update, like an item being placed in a shopping cart on an e-commerce website. Events can either carry the state (the item purchased, its price, and a delivery address) or events can be identifiers (a notification that an order was shipped).
____

<<<

*And for comparison, Red Hat's definition :-*

****

[quote, Red Hat, https://www.redhat.com/en/topics/integration/what-is-event-driven-architecture]
____
Event-driven architecture is a *software architecture* and model for *application design*. With an event-driven system, the *capture, communication, processing, and persistence* of events are the core structure of the solution. This differs from a traditional request-driven model.

Many modern application designs are event-driven, such as customer engagement frameworks that must utilize customer data in real time. Event-driven apps can be created in *any programming language* because event-driven is a programming approach, not a language. Event-driven architecture enables minimal coupling, which makes it a good option for modern, distributed application architectures.

An event-driven architecture is loosely coupled because event producers don’t know which event consumers are listening for an event, and the event doesn’t know what the consequences are of its occurrence.
____

****

= Infrastructure 

include::{chapters-path}infra/storage/storage.adoc[leveloffset=+1]

<<<

include::{chapters-path}infra/serverless/serverless.adoc[leveloffset=+1]

<<<

include::{chapters-path}infra/streaming/amq.adoc[leveloffset=+1]

<<<

== Consclusion

= Integration

include::{chapters-path}integration/camelk.adoc[leveloffset=+1]

<<<

include::{chapters-path}integration/debezium.adoc[leveloffset=+1]

<<<

include::{chapters-path}integration/quarkus.adoc[leveloffset=+1]

<<<

include::{chapters-path}integration/serviceregistry.adoc[leveloffset=+1]

<<<

== Conclusion

= Monitoring

== x

[index]
== Index
<<<
== YouTube Play List

****
[INFORMATION]
.YouTube Play List
Establish an EDA Platform on OpenShift - https://www.youtube.com/watch?v=5kqyFDlyv54&list=PLJhX_m4u3PRGoSjHpHJrUHWGEzVHz5G6P
****
 