= Serverless

:doctype: book
:icons: font
:hide-uri-scheme:

image::serverless.svg[]

== Capabilities

((OpenShift Serverless)) gives our EDA Platform the infrastructure to create Cloud Native Eventing and Serving capabilities.

On the serving side, it gives us access to automatic scaling and rapid deployment of applications. 

Scaling includes traffic-splitting across different versions, flexible routing and scale to zero, which saves resources if deployment is not in use. 

Eventing opens a host of features directly related to EDA processing, channels (publish/subscribe), broker (filter based subscription) and ((Cloud Events)).

((CloudEvents)) forms an important part of EDA, and acts as the internal payload definition, with typically HTTP as the communication protocol.

A sample ((CloudEvent)):

[source, json]
----
{
    "specversion":"1.0",
    "type":"dev.knative.samples.helloworld",
    "source":"dev.knative.samples/helloworldsource",
    "id":"536808d3-88be-4077-9d7a-a3f162705f79",
    "data":{"msg":"Hello Knative2!"}
}
----

*CloudEvents* caters for the following features:

- Consistency
- Accesibility
- Protability

<<<

== Role in EDA Platform

Serverless handles the internal eventing in a Cloud Native environment. Not only does it allow to scale on demand (or lack of), but it also provides a canonical message model, based on Cloud Events.

****
[TIP]
.Serverless Documentation
OpenShift Documentation 
    https://access.redhat.com/documentation/en-us/OpenShift_container_platform/4.10/html/serverless/index
****

****
[TIP]
.CloudEvents
cloudevents 
    https://cloudevents.io/
****

****
[INFORMATION]
.YouTube Video
Installing Serverless on OpenShift 
    https://youtu.be/JQd4aqeBtc8
****

