:doctype: book
:icons: font
:hide-uri-scheme:

= Serverless

== Capabilities

Openshift Serverless gives our EDA Platform the infrastructure to create Cloud Native Eventing and Serving capabilities.

On the serving side, it gives us access to automatic scaling and rapid deployment of applications. 

Scaling includes traffic-splitting across different versions, flexible routing and scale to zero, which saves resources if deployment is not in use. 

Eventing opens a host of features directly related to EDA processing, channels (publish/subscribe), broker (filter based subscription) and Cloud Events.

Cloud Events forms an important part of EDA, and acts as the internal payload definition, with typically HTTP as the communication protocol.

-- Add samples https://github.com/cloudevents/spec/blob/main/cloudevents/formats/json-format.md

****
[TIP]
.Serverless Documentation
Openshift Documentation 
https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation

****

****
[INFORMATION]
.YouTube Video
Installing ODF on Red Hat Virtualization
****